{% set version = "2.1.8" %}

package:
  name: ncview
  version: {{ version }}

source:
  url: ftp://cirrus.ucsd.edu/pub/ncview/ncview-{{ version }}.tar.gz
  sha256: e8badc507b9b774801288d1c2d59eb79ab31b004df4858d0674ed0d87dfc91be
  patches:
    - 0000-change_pnglib_suffix.patch  # [osx]
    - 0001-remove-same-compiler-test.patch

build:
  number: 5
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - hdf5
    - libnetcdf
    - libpng
    - udunits2
    - xorg-libxaw  # [not osx]
    - zlib
  run:
    - hdf5
    - libnetcdf
    - libpng
    - udunits2
    - xorg-libxaw  # [not osx]
    - zlib

test:
  commands:
    - test -f $PREFIX/bin/ncview
    - test -x $PREFIX/bin/ncview

about:
  home: http://meteora.ucsd.edu/~pierce/ncview_home_page.html
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Visual browser for netCDF format files'

  description: |
    Ncview is a visual browser for netCDF format files. Typically you
    would use ncview to get a quick and easy, push-button look at your
    netCDF files. You can view simple movies of the data, view along
    various dimensions, take a look at the actual data values, change
    color maps, invert the data, etc.

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - xylar
