travis:
  secure:
    BINSTAR_TOKEN: TJXjOTckDUaobee+YddIqUV84i4qRgwaLQ2ckV7kG63CRx+xN8wCT2xBh4ya497Nh2bUR/gtTtNUkn6Cjeq1rB/+z1u5E6BeIa/XQspHkblrnOAm6fRKPwr0laSmxBpA0ly2F+nldM55O/utsjVhscHk0FkR0cy8sLm18SiBdqL7LiM3Ne/uI0uZ2OaF9RLNSBZ+p+SB/Q1gL2JtlIov713kJBMiog2cf5t2axLP+KsWqJMhOl15tQNl2G/KPo7jPSpDKOubW/FHDXFq2K1uriVPiXHjiNDoQDRZNqIQPh/WgOqitrLZ68fGfCI1z41ZqocDoZ707eRT9cfBSnFyEMHdoPVfxmZjh3ZfkLQlyG5mtkhTHqv0bsoTv+xY4O9+v1P2YIc8r+jCR3IjiU2rCjwKIDid0568dEKAY91h1By6gTETcEkKhZ/mIQ2UscUlMQE2vb3ZonE/gZfwTvRIWo/rRV+hD/0Iu7Y22kDbZOlYm53Y8zmk7J6UTvwftXKmxfC2FNzBrhityeQvTZHgj6EtO1ObRJhkAXF+zKyR9V+A5IJnjaWv8usTwJdLXH7f3iZ1dgVL8hp5LJhoiQI/f4GwKYeq/C7aLKU0MqnVkOtZLrQU0qYpX9ipWXtVljNcuzgDCoU/IXWZGX33foKzy1XzhRYaE3+FcgFUvVeSbK4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
